name: Build kyaboard firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v3

      - name: Clone ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install west
        run: pip install west

      - name: Init west
        run: |
          cd zmk
          west init -l app
          west update
          west zephyr-export

      - name: Build kyaboard firmware
        run: |
          west build -s zmk/app -d build/left -- -DSHIELD=kyaboard -DBOARD=xiao_ble -DZMK_CONFIG=${{ github.workspace }}/config

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: kyaboard-firmware
          path: build/left/zephyr/zmk.uf2
