name: Build kyaboard firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install west
        run: pip install west

      - name: Initialize west
        run: west init -l config

      - name: Update west modules
        run: west update

      - name: Export Zephyr CMake package
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -d build/kyaboard -b xiao_ble -- -DSHIELD=kyaboard -DZMK_CONFIG=${{ github.workspace }}/config
