name: Build kyaboard firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up output directory
        run: mkdir -p build

      - name: Build kyaboard firmware
        run: |
          west init -l config
          west update
          west build -s zmk/app -d build/kyaboard -b xiao_ble -- -DSHIELD=kyaboard

- name: Upload firmware
  uses: actions/upload-artifact@v3
  with:
    name: firmware
    path: build/zephyr/zmk.uf2

        with:
          name: kyaboard-firmware
          path: build/kyaboard/zephyr/zmk.uf2
